server:
  port: 11001

spring:
  profiles:
    active: sharding-databases
  application:
    name: sharding-jdbc-demo

zlt:
  datasource:
    ip: 172.16.90.163
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.sharding.demo.model
  global-config:
    db-config:
      id-type: ID_WORKER
